import { BlitzEvent, BlitzJoinRequest, Course, InternalMessage, RepAvailabilitySlot, SaleOrder, UserProfile } from '../types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user_owner_gurpreet',
    email: 'gurpreet@eclipsemarketingagency.org',
    firstName: 'Gurpreet',
    lastName: 'Multani',
    displayName: 'Gurpreet Multani',
    role: 'Admin',
    title: 'Chief Executive & Founder',
    dateOfBirth: '1992-04-15',
    shirtSize: 'L',
    phone: '(555) 312-8899',
    emergencyContact: {
      name: 'Simran Multani',
      phone: '(555) 312-8890',
      relationship: 'Spouse',
    },
    idPhotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    badgePhotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    directDeposit: {
      bankName: 'JPMorgan Chase Bank, N.A.',
      accountNumber: '••••••••4812',
      routingNumber: '111000614',
      accountType: 'checking',
      taxIdType: 'EIN',
      taxIdNumber: 'XX-XXX9104',
    },
    fiberAgreement: {
      status: 'signed',
      signedDate: '2026-01-10',
      version: 'v2026.1-master',
    },
    travelProfile: {
      homeAirport: 'DFW - Dallas/Fort Worth',
      ableToTravel: true,
      smsTravelUpdatesConsent: true,
    },
    payRates: {
      'AT&T Fiber': 320,
      'Frontier Fiber': 340,
      'Quantum Fiber': 310,
      'Brightspeed': 290,
      'Spectrum Gig': 280,
      'Kinetic Fiber': 300,
    },
    stats: {
      installs: 142,
      cancels: 8,
      scheduled: 18,
      chargebacks: 1,
      totalSales: 169,
      installRate: 94.6,
      cancelRate: 4.7,
      totalCommission: 48960,
    },
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-09-25T12:00:00Z',
  },
  {
    id: 'user_mgr_marcus',
    email: 'marcus.vance@eclipsedashboard.com',
    firstName: 'Marcus',
    lastName: 'Vance',
    displayName: 'Marcus Vance',
    role: 'Manager',
    title: 'Regional Blitz Operations Director',
    managerId: 'user_owner_gurpreet',
    managerName: 'Gurpreet Multani',
    dateOfBirth: '1994-08-22',
    shirtSize: 'XL',
    phone: '(555) 782-4411',
    emergencyContact: {
      name: 'Angela Vance',
      phone: '(555) 782-4412',
      relationship: 'Spouse',
    },
    badgePhotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    directDeposit: {
      bankName: 'Bank of America',
      accountNumber: '••••••••6290',
      routingNumber: '026009593',
      accountType: 'checking',
      taxIdType: 'SSN',
      taxIdNumber: 'XXX-XX-5582',
    },
    fiberAgreement: {
      status: 'signed',
      signedDate: '2026-02-01',
      version: 'v2026.1-master',
    },
    travelProfile: {
      homeAirport: 'ATL - Hartsfield-Jackson Atlanta',
      ableToTravel: true,
      smsTravelUpdatesConsent: true,
    },
    payRates: {
      'AT&T Fiber': 290,
      'Frontier Fiber': 310,
      'Quantum Fiber': 280,
      'Brightspeed': 260,
      'Spectrum Gig': 250,
      'Kinetic Fiber': 270,
    },
    stats: {
      installs: 96,
      cancels: 7,
      scheduled: 14,
      chargebacks: 2,
      totalSales: 119,
      installRate: 93.2,
      cancelRate: 5.8,
      totalCommission: 31200,
    },
    createdAt: '2026-01-15T08:00:00Z',
    updatedAt: '2026-09-25T12:00:00Z',
  },
  {
    id: 'user_rep_jordan',
    email: 'jordan.hayes@eclipsedashboard.com',
    firstName: 'Jordan',
    lastName: 'Hayes',
    displayName: 'Jordan Hayes',
    role: 'Representative',
    title: 'Senior Fiber Field Specialist',
    managerId: 'user_mgr_marcus',
    managerName: 'Marcus Vance',
    dateOfBirth: '1998-11-04',
    shirtSize: 'M',
    phone: '(555) 438-9921',
    emergencyContact: {
      name: 'Robert Hayes',
      phone: '(555) 438-9920',
      relationship: 'Father',
    },
    badgePhotoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80',
    directDeposit: {
      bankName: 'Wells Fargo Bank',
      accountNumber: '••••••••7731',
      routingNumber: '121000247',
      accountType: 'checking',
      taxIdType: 'SSN',
      taxIdNumber: 'XXX-XX-8419',
    },
    fiberAgreement: {
      status: 'coming_soon',
      version: 'v2026.2-preview',
    },
    travelProfile: {
      homeAirport: 'ORD - Chicago O\'Hare',
      ableToTravel: true,
      smsTravelUpdatesConsent: true,
    },
    payRates: {
      'AT&T Fiber': 260,
      'Frontier Fiber': 280,
      'Quantum Fiber': 250,
      'Brightspeed': 230,
      'Spectrum Gig': 220,
      'Kinetic Fiber': 240,
    },
    stats: {
      installs: 58,
      cancels: 5,
      scheduled: 11,
      chargebacks: 1,
      totalSales: 75,
      installRate: 92.0,
      cancelRate: 6.6,
      totalCommission: 17400,
    },
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-09-25T12:00:00Z',
  },
  {
    id: 'user_rep_elena',
    email: 'elena.rivera@eclipsedashboard.com',
    firstName: 'Elena',
    lastName: 'Rivera',
    displayName: 'Elena Rivera',
    role: 'Representative',
    title: 'Top Gun Field Specialist',
    managerId: 'user_mgr_marcus',
    managerName: 'Marcus Vance',
    dateOfBirth: '1999-03-18',
    shirtSize: 'S',
    phone: '(555) 290-7711',
    emergencyContact: {
      name: 'Maria Rivera',
      phone: '(555) 290-7710',
      relationship: 'Mother',
    },
    badgePhotoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    directDeposit: {
      bankName: 'PNC Bank',
      accountNumber: '••••••••1104',
      routingNumber: '043000096',
      accountType: 'checking',
      taxIdType: 'SSN',
      taxIdNumber: 'XXX-XX-3901',
    },
    fiberAgreement: {
      status: 'signed',
      signedDate: '2026-04-12',
      version: 'v2026.1-master',
    },
    travelProfile: {
      homeAirport: 'MCO - Orlando International',
      ableToTravel: true,
      smsTravelUpdatesConsent: true,
    },
    payRates: {
      'AT&T Fiber': 260,
      'Frontier Fiber': 280,
      'Quantum Fiber': 250,
      'Brightspeed': 230,
      'Spectrum Gig': 220,
      'Kinetic Fiber': 240,
    },
    stats: {
      installs: 49,
      cancels: 4,
      scheduled: 8,
      chargebacks: 0,
      totalSales: 61,
      installRate: 92.4,
      cancelRate: 6.5,
      totalCommission: 14820,
    },
    createdAt: '2026-04-10T08:00:00Z',
    updatedAt: '2026-09-25T12:00:00Z',
  },
  {
    id: 'user_rep_tyler',
    email: 'tyler.chen@eclipsedashboard.com',
    firstName: 'Tyler',
    lastName: 'Chen',
    displayName: 'Tyler Chen',
    role: 'Representative',
    title: 'Fiber Blitz Closer',
    managerId: 'user_mgr_marcus',
    managerName: 'Marcus Vance',
    dateOfBirth: '2001-06-30',
    shirtSize: 'L',
    phone: '(555) 601-3829',
    emergencyContact: {
      name: 'Karen Chen',
      phone: '(555) 601-3820',
      relationship: 'Sister',
    },
    badgePhotoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    directDeposit: {
      bankName: 'Chase Bank',
      accountNumber: '••••••••9843',
      routingNumber: '111000614',
      accountType: 'checking',
      taxIdType: 'SSN',
      taxIdNumber: 'XXX-XX-1192',
    },
    fiberAgreement: {
      status: 'coming_soon',
      version: 'v2026.2-preview',
    },
    travelProfile: {
      homeAirport: 'IAH - Houston George Bush',
      ableToTravel: true,
      smsTravelUpdatesConsent: true,
    },
    payRates: {
      'AT&T Fiber': 250,
      'Frontier Fiber': 270,
      'Quantum Fiber': 240,
      'Brightspeed': 220,
      'Spectrum Gig': 210,
      'Kinetic Fiber': 230,
    },
    stats: {
      installs: 38,
      cancels: 3,
      scheduled: 7,
      chargebacks: 0,
      totalSales: 48,
      installRate: 92.6,
      cancelRate: 6.2,
      totalCommission: 10450,
    },
    createdAt: '2026-05-15T08:00:00Z',
    updatedAt: '2026-09-25T12:00:00Z',
  }
];

export const INITIAL_BLITZES: BlitzEvent[] = [
  {
    id: 'blitz_tx_central_surge',
    title: 'Central Texas & DFW Mega Blitz',
    state: 'TX',
    city: 'Dallas / Fort Worth & Austin',
    ispPartner: 'AT&T Fiber',
    startDate: '2026-09-20',
    endDate: '2026-10-04',
    status: 'active',
    targetGoal: 450,
    currentSales: 312,
    installedCount: 228,
    maxSpots: 40,
    bookedCount: 36,
    hotelHub: 'Omni Dallas Downtown & Sonesta Austin Hub',
    dailyPerDiem: 75,
    description: 'High-density Greenfield fiber rollout covering over 42,000 newly lit residential addresses. Full turf management, daily transport shuttles, and live team dispatch.',
    leadCoordinator: 'Marcus Vance',
    bookedUserIds: ['user_rep_jordan', 'user_rep_elena', 'user_rep_tyler', 'user_mgr_marcus'],
  },
  {
    id: 'blitz_fl_suncoast',
    title: 'Tampa Bay & Suncoast Frontier Blitz',
    state: 'FL',
    city: 'Tampa & St. Petersburg',
    ispPartner: 'Frontier Fiber',
    startDate: '2026-09-22',
    endDate: '2026-10-06',
    status: 'active',
    targetGoal: 320,
    currentSales: 215,
    installedCount: 164,
    maxSpots: 35,
    bookedCount: 31,
    hotelHub: 'Grand Hyatt Tampa Bay',
    dailyPerDiem: 80,
    description: 'Frontier 2-Gig and 5-Gig fiber blitz across newly expanded Tampa Bay coastal corridors. Unmatched closing rates against legacy coax providers.',
    leadCoordinator: 'Marcus Vance',
    bookedUserIds: ['user_rep_elena', 'user_rep_jordan'],
  },
  {
    id: 'blitz_nc_carolina_sprint',
    title: 'Charlotte & Piedmont Fiber Offensive',
    state: 'NC',
    city: 'Charlotte & Concord',
    ispPartner: 'AT&T Fiber',
    startDate: '2026-10-08',
    endDate: '2026-10-22',
    status: 'upcoming',
    targetGoal: 280,
    currentSales: 0,
    installedCount: 0,
    maxSpots: 30,
    bookedCount: 22,
    hotelHub: 'The Westin Charlotte Uptown',
    dailyPerDiem: 75,
    description: 'Fall expansion surge hitting high-income sub-divisions and planned communities with verified lit fiber ONTs ready for fast 48-hour turnarounds.',
    leadCoordinator: 'Gurpreet Multani',
    bookedUserIds: ['user_rep_jordan', 'user_rep_tyler'],
  },
  {
    id: 'blitz_az_desert_quantum',
    title: 'Phoenix East Valley Quantum Rush',
    state: 'AZ',
    city: 'Phoenix, Scottsdale & Mesa',
    ispPartner: 'Quantum Fiber',
    startDate: '2026-10-15',
    endDate: '2026-10-29',
    status: 'upcoming',
    targetGoal: 250,
    currentSales: 0,
    installedCount: 0,
    maxSpots: 28,
    bookedCount: 14,
    hotelHub: 'JW Marriott Desert Ridge Resort',
    dailyPerDiem: 85,
    description: 'Prime weather season blitz across 18 new CO nodes. Top earner incentive bonus: $1,500 cash for 30+ installs.',
    leadCoordinator: 'Marcus Vance',
    bookedUserIds: ['user_rep_elena'],
  },
  {
    id: 'blitz_oh_columbus_front',
    title: 'Columbus Metro Brightspeed & Spectrum Blitz',
    state: 'OH',
    city: 'Columbus & Dublin',
    ispPartner: 'Brightspeed Fiber',
    startDate: '2026-11-02',
    endDate: '2026-11-16',
    status: 'upcoming',
    targetGoal: 200,
    currentSales: 0,
    installedCount: 0,
    maxSpots: 25,
    bookedCount: 9,
    hotelHub: 'Hilton Columbus Downtown',
    dailyPerDiem: 70,
    description: 'Midwest expansion targeting newly completed FTTH overbuild zones with zero competitive fiber options.',
    leadCoordinator: 'Gurpreet Multani',
    bookedUserIds: [],
  },
  {
    id: 'blitz_ga_atlanta_north',
    title: 'North Atlanta Perimeter Kinetic Blitz',
    state: 'GA',
    city: 'Alpharetta & Roswell',
    ispPartner: 'Kinetic Fiber',
    startDate: '2026-11-10',
    endDate: '2026-11-24',
    status: 'upcoming',
    targetGoal: 220,
    currentSales: 0,
    installedCount: 0,
    maxSpots: 25,
    bookedCount: 7,
    hotelHub: 'The Hotel at Avalon Alpharetta',
    dailyPerDiem: 75,
    description: 'High-speed fiber rollout in prime suburban territory. Pre-qualified addresses provided via mapped turf app.',
    leadCoordinator: 'Marcus Vance',
    bookedUserIds: [],
  },
  {
    id: 'blitz_fl_orlando_surge',
    title: 'Orlando Metro Frontier Super Blitz',
    state: 'FL',
    city: 'Orlando & Kissimmee',
    ispPartner: 'Frontier Fiber',
    startDate: '2026-08-05',
    endDate: '2026-08-19',
    status: 'completed',
    targetGoal: 300,
    currentSales: 318,
    installedCount: 298,
    maxSpots: 35,
    bookedCount: 35,
    hotelHub: 'Hyatt Regency Grand Cypress Orlando',
    dailyPerDiem: 80,
    description: 'Record-setting multi-team deployment across Orange and Osceola counties. 106% goal achievement with $42,000 in rep payout bonuses.',
    leadCoordinator: 'Marcus Vance',
    bookedUserIds: ['user_rep_jordan', 'user_rep_tyler', 'user_mgr_marcus'],
  },
  {
    id: 'blitz_tx_austin_greenfield',
    title: 'Austin Tech Corridor Greenfield Blitz',
    state: 'TX',
    city: 'Austin, Round Rock & Buda',
    ispPartner: 'AT&T Fiber',
    startDate: '2026-07-10',
    endDate: '2026-07-24',
    status: 'completed',
    targetGoal: 350,
    currentSales: 382,
    installedCount: 354,
    maxSpots: 40,
    bookedCount: 40,
    hotelHub: 'Sonesta Austin Downtown',
    dailyPerDiem: 75,
    description: 'Greenfield subdivision deployment achieving standard-setting 93% install rate and top 5 company record customer retention.',
    leadCoordinator: 'Gurpreet Multani',
    bookedUserIds: ['user_rep_jordan', 'user_rep_elena'],
  },
  {
    id: 'blitz_nc_triangle_mastery',
    title: 'Raleigh-Durham Research Triangle Blitz',
    state: 'NC',
    city: 'Raleigh, Durham & Cary',
    ispPartner: 'AT&T Fiber',
    startDate: '2026-06-08',
    endDate: '2026-06-22',
    status: 'completed',
    targetGoal: 240,
    currentSales: 255,
    installedCount: 242,
    maxSpots: 25,
    bookedCount: 25,
    hotelHub: 'The Umstead Hotel & Spa Cary',
    dailyPerDiem: 75,
    description: 'Sprint blitz hitting high-speed residential fiber clusters with complete ONT pre-provisioning.',
    leadCoordinator: 'Marcus Vance',
    bookedUserIds: ['user_rep_elena'],
  }
];

export const INITIAL_JOIN_REQUESTS: BlitzJoinRequest[] = [
  {
    id: 'req_101',
    blitzId: 'blitz_az_desert_quantum',
    blitzTitle: 'Phoenix East Valley Quantum Rush',
    blitzState: 'AZ',
    blitzCity: 'Phoenix, Scottsdale & Mesa',
    blitzDates: '2026-10-15 to 2026-10-29',
    userId: 'user_rep_tyler',
    userName: 'Tyler Chen',
    userEmail: 'tyler.chen@eclipsedashboard.com',
    userRole: 'Representative',
    userHomeAirport: 'IAH - Houston George Bush',
    requestNotes: 'Excited for the Quantum Fiber rollout! Have hit 92% install rate in Texas and ready to lead turf in Scottsdale.',
    roommatePreference: 'Jordan Hayes or single room',
    pledgedInstalls: 25,
    status: 'pending',
    submittedAt: '2026-09-24T14:30:00Z',
  },
  {
    id: 'req_102',
    blitzId: 'blitz_nc_carolina_sprint',
    blitzTitle: 'Charlotte & Piedmont Fiber Offensive',
    blitzState: 'NC',
    blitzCity: 'Charlotte & Concord',
    blitzDates: '2026-10-08 to 2026-10-22',
    userId: 'user_rep_elena',
    userName: 'Elena Rostova',
    userEmail: 'elena.rostova@eclipsedashboard.com',
    userRole: 'Representative',
    userHomeAirport: 'MIA - Miami International',
    requestNotes: 'Requesting early flight Sunday morning. Ready for high-density suburban turf.',
    roommatePreference: 'Standard team roommate assignment',
    pledgedInstalls: 35,
    status: 'approved',
    submittedAt: '2026-09-22T09:15:00Z',
    reviewedBy: 'Marcus Vance',
    reviewedAt: '2026-09-23T11:00:00Z',
    reviewNotes: 'Approved based on stellar Florida track record.',
  }
];

export const INITIAL_AVAILABILITY: RepAvailabilitySlot[] = [
  {
    id: 'avail_1',
    userId: 'user_rep_jordan',
    userName: 'Jordan Hayes',
    startDate: '2026-09-18',
    endDate: '2026-10-06',
    status: 'available',
    notes: 'Fully available for Texas and Suncoast deployment.',
    createdAt: '2026-09-15T10:00:00Z',
  },
  {
    id: 'avail_2',
    userId: 'user_rep_jordan',
    userName: 'Jordan Hayes',
    startDate: '2026-10-07',
    endDate: '2026-10-24',
    status: 'available',
    notes: 'Cleared for East Coast / Carolinas tour.',
    createdAt: '2026-09-16T12:00:00Z',
  },
  {
    id: 'avail_3',
    userId: 'user_rep_jordan',
    userName: 'Jordan Hayes',
    startDate: '2026-10-25',
    endDate: '2026-10-31',
    status: 'unavailable',
    notes: 'Family event / Blackout dates.',
    createdAt: '2026-09-20T16:00:00Z',
  },
  {
    id: 'avail_4',
    userId: 'user_rep_elena',
    userName: 'Elena Rostova',
    startDate: '2026-09-20',
    endDate: '2026-10-30',
    status: 'available',
    notes: 'Ready for all travel blitzes.',
    createdAt: '2026-09-18T08:00:00Z',
  },
  {
    id: 'avail_5',
    userId: 'user_rep_tyler',
    userName: 'Tyler Chen',
    startDate: '2026-10-10',
    endDate: '2026-11-15',
    status: 'available',
    notes: 'Available for West / Southwest territory.',
    createdAt: '2026-09-21T09:30:00Z',
  }
];

export const INITIAL_SALES: SaleOrder[] = [
  {
    id: 'sale_101',
    orderNumber: 'FB-98201',
    repId: 'user_rep_jordan',
    repName: 'Jordan Hayes',
    repRole: 'Representative',
    uplineManagerId: 'user_mgr_marcus',
    uplineManagerName: 'Marcus Vance',
    customerName: 'Robert Vance Jr.',
    customerPhone: '(214) 555-0192',
    customerEmail: 'robert.vance@gmail.com',
    address: '4921 Lone Star Trail',
    city: 'Fort Worth',
    state: 'TX',
    zipCode: '76109',
    ispProgram: 'AT&T Fiber',
    speedTier: '1 Gig',
    orderDate: '2026-09-21',
    installDate: '2026-09-23',
    status: 'installed',
    payout: 260,
    blitzId: 'blitz_tx_central_surge',
    blitzName: 'Central Texas & DFW Mega Blitz',
    notes: 'Same-day technician verified. Customer opted for Wi-Fi 6 gateway.',
    createdAt: '2026-09-21T14:32:00Z',
  },
  {
    id: 'sale_102',
    orderNumber: 'FB-98202',
    repId: 'user_rep_jordan',
    repName: 'Jordan Hayes',
    repRole: 'Representative',
    uplineManagerId: 'user_mgr_marcus',
    uplineManagerName: 'Marcus Vance',
    customerName: 'Sarah Jenkins',
    customerPhone: '(214) 555-7731',
    customerEmail: 's.jenkins@outlook.com',
    address: '1084 Bluebonnet Way',
    city: 'Arlington',
    state: 'TX',
    zipCode: '76011',
    ispProgram: 'AT&T Fiber',
    speedTier: '500 Mbps',
    orderDate: '2026-09-22',
    installDate: '2026-09-24',
    status: 'installed',
    payout: 260,
    blitzId: 'blitz_tx_central_surge',
    blitzName: 'Central Texas & DFW Mega Blitz',
    notes: 'Switching from Spectrum cable. Free install confirmed.',
    createdAt: '2026-09-22T16:15:00Z',
  },
  {
    id: 'sale_103',
    orderNumber: 'FB-98203',
    repId: 'user_rep_jordan',
    repName: 'Jordan Hayes',
    repRole: 'Representative',
    uplineManagerId: 'user_mgr_marcus',
    uplineManagerName: 'Marcus Vance',
    customerName: 'Michael Delgado',
    customerPhone: '(817) 555-8841',
    address: '772 Oakridge Terrace',
    city: 'Dallas',
    state: 'TX',
    zipCode: '75204',
    ispProgram: 'AT&T Fiber',
    speedTier: '1 Gig',
    orderDate: '2026-09-23',
    installDate: '2026-09-26',
    status: 'scheduled',
    payout: 260,
    blitzId: 'blitz_tx_central_surge',
    blitzName: 'Central Texas & DFW Mega Blitz',
    notes: 'Dispatch window 1:00 PM - 3:00 PM. Gate code #4910.',
    createdAt: '2026-09-23T11:45:00Z',
  },
  {
    id: 'sale_104',
    orderNumber: 'FB-98204',
    repId: 'user_rep_jordan',
    repName: 'Jordan Hayes',
    repRole: 'Representative',
    uplineManagerId: 'user_mgr_marcus',
    uplineManagerName: 'Marcus Vance',
    customerName: 'Patricia Morales',
    customerPhone: '(214) 555-3392',
    address: '315 Canyon Ridge Dr',
    city: 'Plano',
    state: 'TX',
    zipCode: '75024',
    ispProgram: 'AT&T Fiber',
    speedTier: '2 Gig',
    orderDate: '2026-09-24',
    installDate: '2026-09-27',
    status: 'scheduled',
    payout: 260,
    blitzId: 'blitz_tx_central_surge',
    blitzName: 'Central Texas & DFW Mega Blitz',
    notes: 'Power user / gamer household. Enthusiastic about 2 Gig.',
    createdAt: '2026-09-24T18:20:00Z',
  },
  {
    id: 'sale_105',
    orderNumber: 'FB-98205',
    repId: 'user_rep_jordan',
    repName: 'Jordan Hayes',
    repRole: 'Representative',
    uplineManagerId: 'user_mgr_marcus',
    uplineManagerName: 'Marcus Vance',
    customerName: 'David Sterling',
    customerPhone: '(817) 555-1102',
    address: '904 Heritage Lake Court',
    city: 'Keller',
    state: 'TX',
    zipCode: '76248',
    ispProgram: 'AT&T Fiber',
    speedTier: '1 Gig',
    orderDate: '2026-09-20',
    installDate: '2026-09-22',
    status: 'cancelled',
    payout: 0,
    blitzId: 'blitz_tx_central_surge',
    blitzName: 'Central Texas & DFW Mega Blitz',
    notes: 'Landlord refused drop cable across property fence line.',
    createdAt: '2026-09-20T10:10:00Z',
  },
  {
    id: 'sale_106',
    orderNumber: 'FB-98206',
    repId: 'user_rep_elena',
    repName: 'Elena Rivera',
    repRole: 'Representative',
    uplineManagerId: 'user_mgr_marcus',
    uplineManagerName: 'Marcus Vance',
    customerName: 'Carlos Santillan',
    customerPhone: '(813) 555-3819',
    address: '1420 Bayshore Blvd #4B',
    city: 'Tampa',
    state: 'FL',
    zipCode: '33606',
    ispProgram: 'Frontier Fiber',
    speedTier: '1 Gig',
    orderDate: '2026-09-22',
    installDate: '2026-09-24',
    status: 'installed',
    payout: 280,
    blitzId: 'blitz_fl_suncoast',
    blitzName: 'Tampa Bay & Suncoast Frontier Blitz',
    notes: 'ONT installed in utility closet. Speed test showed 940/940 Mbps.',
    createdAt: '2026-09-22T13:40:00Z',
  },
  {
    id: 'sale_107',
    orderNumber: 'FB-98207',
    repId: 'user_rep_elena',
    repName: 'Elena Rivera',
    repRole: 'Representative',
    uplineManagerId: 'user_mgr_marcus',
    uplineManagerName: 'Marcus Vance',
    customerName: 'Melissa Howard',
    customerPhone: '(813) 555-9014',
    address: '602 Dolphin Crest Way',
    city: 'St. Petersburg',
    state: 'FL',
    zipCode: '33701',
    ispProgram: 'Frontier Fiber',
    speedTier: '2 Gig',
    orderDate: '2026-09-23',
    installDate: '2026-09-25',
    status: 'installed',
    payout: 280,
    blitzId: 'blitz_fl_suncoast',
    blitzName: 'Tampa Bay & Suncoast Frontier Blitz',
    notes: 'Immediate tech approval. Signed digital work order.',
    createdAt: '2026-09-23T15:20:00Z',
  },
  {
    id: 'sale_108',
    orderNumber: 'FB-98208',
    repId: 'user_rep_elena',
    repName: 'Elena Rivera',
    repRole: 'Representative',
    uplineManagerId: 'user_mgr_marcus',
    uplineManagerName: 'Marcus Vance',
    customerName: 'Gregory King',
    customerPhone: '(727) 555-6677',
    address: '3819 Palm Grove Ct',
    city: 'Clearwater',
    state: 'FL',
    zipCode: '33755',
    ispProgram: 'Frontier Fiber',
    speedTier: '500 Mbps',
    orderDate: '2026-09-24',
    installDate: '2026-09-28',
    status: 'scheduled',
    payout: 280,
    blitzId: 'blitz_fl_suncoast',
    blitzName: 'Tampa Bay & Suncoast Frontier Blitz',
    notes: 'Customer working from home, request morning slot.',
    createdAt: '2026-09-24T17:05:00Z',
  },
  {
    id: 'sale_109',
    orderNumber: 'FB-98209',
    repId: 'user_rep_tyler',
    repName: 'Tyler Chen',
    repRole: 'Representative',
    uplineManagerId: 'user_mgr_marcus',
    uplineManagerName: 'Marcus Vance',
    customerName: 'Brandon Walsh',
    customerPhone: '(214) 555-4902',
    address: '2214 Sunset Ridge',
    city: 'Grapevine',
    state: 'TX',
    zipCode: '76051',
    ispProgram: 'AT&T Fiber',
    speedTier: '1 Gig',
    orderDate: '2026-09-22',
    installDate: '2026-09-24',
    status: 'installed',
    payout: 250,
    blitzId: 'blitz_tx_central_surge',
    blitzName: 'Central Texas & DFW Mega Blitz',
    notes: 'Closed in 12 minutes. Customer hated previous bill spikes.',
    createdAt: '2026-09-22T11:10:00Z',
  },
  {
    id: 'sale_110',
    orderNumber: 'FB-98210',
    repId: 'user_rep_tyler',
    repName: 'Tyler Chen',
    repRole: 'Representative',
    uplineManagerId: 'user_mgr_marcus',
    uplineManagerName: 'Marcus Vance',
    customerName: 'Hannah Foster',
    customerPhone: '(214) 555-6619',
    address: '1105 Pecan Hollow',
    city: 'Southlake',
    state: 'TX',
    zipCode: '76092',
    ispProgram: 'AT&T Fiber',
    speedTier: '5 Gig',
    orderDate: '2026-09-23',
    installDate: '2026-09-25',
    status: 'chargeback',
    payout: -250,
    blitzId: 'blitz_tx_central_surge',
    blitzName: 'Central Texas & DFW Mega Blitz',
    notes: 'Cancelled post-install within 24hr due to HOA exterior conduit protest.',
    createdAt: '2026-09-23T14:50:00Z',
  },
  {
    id: 'sale_111',
    orderNumber: 'FB-98211',
    repId: 'user_mgr_marcus',
    repName: 'Marcus Vance',
    repRole: 'Manager',
    customerName: 'Dr. Warren Scott',
    customerPhone: '(404) 555-7788',
    address: '880 Peachtree Battle Ave',
    city: 'Atlanta',
    state: 'GA',
    zipCode: '30327',
    ispProgram: 'AT&T Fiber',
    speedTier: '2 Gig',
    orderDate: '2026-09-20',
    installDate: '2026-09-22',
    status: 'installed',
    payout: 290,
    notes: 'Executive home office install with dedicated mesh extenders.',
    createdAt: '2026-09-20T09:30:00Z',
  }
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course_blitz_mastery',
    title: 'Fiber Blitz Mastery: Door Pitch & The 7-Second Hook',
    category: 'Field Sales & Execution',
    badgeTitle: 'Fiber Door Closer Certification',
    description: 'Master the field psychology of door-to-door fiber sales. Learn how to break preoccupation, explain true symmetrical upload speeds, and close homeowners in under 15 minutes.',
    estimatedHours: 2.5,
    level: 'Beginner',
    authorName: 'Gurpreet Multani (Founder & CEO)',
    createdBy: 'user_owner_gurpreet',
    published: true,
    enrolledCount: 48,
    completedCount: 39,
    lessons: [
      {
        id: 'lesson_1_1',
        title: 'The First 7 Seconds: Breaking Preoccupation at the Door',
        durationMinutes: 18,
        videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ', // Standard embed format
        content: `### Why the First 7 Seconds Determine 80% of Blitz Closings

When knocking in a blitz market, you aren't a generic solicitor; you are the **field deployment coordinator** notifying the block that brand-new underground fiber optic infrastructure is officially lit and live.

#### The Triple-Trigger Opening Script:
1. **Physical Position**: Step 2 paces back from the door after knocking. Angle 45 degrees sideways (non-threatening posture). Have your high-vis lanyard badge visible.
2. **The Disruptive Hook**:
> *"Hey, quick courtesy check for the neighborhood! I'm [Name] with the fiber deployment team down on Elmwood. We just finished testing the light levels at the terminal pedestal down the curb, and we're letting everyone know the symmetrical fiber is live today."*
3. **The Pre-Emptive Shift**:
> *"I'm sure you already have either Spectrum or Comcast inside—we're not touching that right now. All we're checking is whether your address was marked for the underground drop line while our boring crew is on the street."*

#### Key Takeaways:
- Never ask *"How are you today?"* (sounds like a telemarketer).
- Frame the visit as an infrastructure activation, not a sales pitch.
- Instantly position fiber as an upgrade they have already paid for through local tax & infrastructure grants.`,
        keyTakeaways: [
          'Stand 2 paces back at a 45-degree angle with badge facing forward',
          'Acknowledge existing cable provider immediately to lower defensive shields',
          'Use infrastructure activation language rather than retail sales words'
        ]
      },
      {
        id: 'lesson_1_2',
        title: 'Symmetrical Fiber vs. Cable Coax: The Whiteboard Pitch',
        durationMinutes: 22,
        content: `### How to Demolish the "I Already Have Fast Internet" Objection

Most homeowners believe that 300 Mbps or 500 Mbps cable internet is "plenty fast." They do not know about **asymmetrical bottlenecking**.

#### The Core Scientific Comparison:
- **Legacy Cable (DOCSIS / Coax)**: Shared copper loop. Downloader gets 400 Mbps down, but only **10 to 20 Mbps upload!** When someone uploads a Zoom video, backs up iPhone iCloud photos, or plays games, the entire house pipeline chokes.
- **Pure Fiber to the Home (FTTH)**: Dedicated glass strands traveling at the speed of light. **1,000 Mbps download AND 1,000 Mbps upload**. Zero buffering, zero latency spikes.

#### The Simple Household Question:
> *"When your phone does an automatic iCloud photo backup at 8 PM, or your kids jump on gaming while you're on a work Zoom—have you noticed that spinning wheel? That's not your Wi-Fi router; that's copper cable's upload bottleneck. Fiber gives you 50 times faster upload so no device in the house ever waits."*`,
        keyTakeaways: [
          'Explain Symmetrical Upload: 1000 Mbps UP and DOWN',
          'Target the real pain: Zoom freezes, smart security cameras lag, iCloud backup congestion',
          'Use the 50x upload speed contrast'
        ]
      },
      {
        id: 'lesson_1_3',
        title: 'Closing the Order: The Paperless Tablet Flow',
        durationMinutes: 15,
        content: `### Locking Down the Dispatch Date
Once the customer understands the price lock and no-contract advantage:
1. Don't ask *"Do you want to do this?"*
2. Ask an **alternate of choice**:
> *"The dispatch crew has two time blocks for your street: Thursday morning between 8 AM and 11 AM, or Friday afternoon between 1 PM and 3 PM. Which works best for you to have the technician plug in the gateway?"*
3. Pull out the tablet, confirm their exact spelling, and schedule the install immediately!`,
        keyTakeaways: [
          'Always use an alternate-of-choice close for scheduling time slots',
          'Secure install dates within 48-72 hours to prevent buyer hesitation',
          'Send immediate confirmation text before walking off the porch'
        ]
      }
    ],
    assignment: {
      id: 'assign_pitch_script',
      title: 'Field Objection Script: The "I Need to Ask My Spouse" Defense',
      deliverableType: 'pitch_script',
      maxPoints: 100,
      instructions: 'Write your verbatim 3-step response when a prospect smiles and says: "This sounds great, but I need to talk to my spouse before making any decisions." Show how you validate their spouse, overcome the delay, and schedule a tentative reservation so they do not lose the free install promotion.'
    },
    quiz: [
      {
        id: 'q1',
        questionType: 'multiple_choice',
        question: 'What is the main technical difference between Fiber and traditional Cable (DOCSIS)?',
        options: [
          'Fiber uses copper wires with higher electrical voltage',
          'Fiber provides 100% symmetrical upload and download speeds via glass light pulses',
          'Cable is faster during rainy weather',
          'There is no difference, it is just branding'
        ],
        correctAnswerIndex: 1,
        explanation: 'Fiber transmits data via laser light through glass strands, allowing equal upload and download speeds (e.g., 1000 Mbps both directions), unlike coax cable which has severely throttled upload speeds.'
      },
      {
        id: 'q2',
        questionType: 'multiple_choice',
        question: 'When knocking on a residential door during a blitz, what is the best physical stance?',
        options: [
          'Lean on the door frame to look comfortable',
          'Stand 6 inches from the peephole with both hands in pockets',
          'Stand 2 paces back at a 45-degree angle with ID badge clearly visible',
          'Ring the doorbell 4 times consecutively'
        ],
        correctAnswerIndex: 2,
        explanation: 'Stepping 2 paces back at a 45-degree angle removes predatory pressure and allows the homeowner to open their door without feeling cornered.'
      },
      {
        id: 'q3',
        questionType: 'multiple_choice',
        question: 'What is an "Alternate of Choice" close when scheduling an installation?',
        options: [
          'Asking "Do you want internet or not?"',
          'Offering two specific appointment windows: "Does Thursday morning or Friday afternoon work better for you?"',
          'Telling them they must call customer service tomorrow',
          'Waiting until they ask to buy'
        ],
        correctAnswerIndex: 1,
        explanation: 'The alternate of choice close guides the customer from deciding IF they want the service to deciding WHEN they want the technician to install it.'
      }
    ]
  },
  {
    id: 'course_compliance_dispatch',
    title: 'Order Accuracy, ONT Placement & Zero-Cancel Dispatching',
    category: 'Operations & Compliance',
    badgeTitle: 'Certified Field Dispatch Specialist',
    description: 'Ensure 95%+ install completion rates. Learn how to verify property easements, qualify ONT exterior fiber drops, prevent same-day cancellations, and eliminate chargebacks.',
    estimatedHours: 1.5,
    level: 'Intermediate',
    authorName: 'Marcus Vance (Ops Director)',
    createdBy: 'user_mgr_marcus',
    published: true,
    enrolledCount: 36,
    completedCount: 30,
    lessons: [
      {
        id: 'lesson_2_1',
        title: 'Verifying Address Qualification & Drop Terminal Proximity',
        durationMinutes: 16,
        content: `### Never Sell an Unserviceable Green Box
Before knocking any turf or submitting a sale:
1. Always run the address in the live carrier portal.
2. Confirm the **MST (Multi-Port Service Terminal)** is within 250 feet of the home foundation.
3. Check for physical aerial vs. buried drop restrictions. If buried, mark the property for utility locate flags (call 811 automatically generated).`,
        keyTakeaways: [
          'Verify MST terminal distance under 250 ft',
          'Mark HOA or private driveway obstructions early',
          'Accurate customer phone numbers are mandatory for dispatch dispatching'
        ]
      },
      {
        id: 'lesson_2_2',
        title: 'The Pre-Install 24-Hour Warm-Up Text Protocol',
        durationMinutes: 14,
        content: `### How Our Top Reps Hold a 94%+ Install Rate
Cancels don't happen because customers don't want fiber; cancels happen because of buyer remorse and missed technician arrivals.

#### The 3-Touch Follow-Up System:
1. **Touch 1 (Evening of Sale)**: Send a welcome text with the order # and install date.
2. **Touch 2 (Day Before Install)**: "Reminder from your Fiber Blitz Rep: Tech dispatch window is tomorrow 8-11am! Make sure someone 18+ is home."
3. **Touch 3 (Morning of Install)**: "The crew is en route. If you need anything, call my cell directly."`,
        keyTakeaways: [
          'Send the 3-Touch text sequence on every sale',
          'Ensures an adult 18+ is home to sign the technician manifest',
          'Reduces missed appointments by over 70%'
        ]
      }
    ],
    assignment: {
      id: 'assign_preinstall_protocol',
      title: 'Craft Your 3-Touch Install Retention Text Sequence',
      deliverableType: 'written_response',
      maxPoints: 100,
      instructions: 'Write out your exact personalized text message templates for Touch 1 (night of sale), Touch 2 (day before install), and Touch 3 (morning of install) including your rep direct line.'
    },
    quiz: [
      {
        id: 'q2_1',
        questionType: 'multiple_choice',
        question: 'Why is an adult 18+ required to be present during the technician visit?',
        options: [
          'Because only adults can use fiber optics',
          'To authorize drilling and equipment installation inside the residence',
          'To pay the technician with physical cash',
          'It is not required'
        ],
        correctAnswerIndex: 1,
        explanation: 'Carriers require legal consent from an adult resident to drill wall access for fiber cables and mount the indoor ONT unit.'
      },
      {
        id: 'q2_2',
        questionType: 'multiple_choice',
        question: 'What is the number one cause of install cancellations?',
        options: [
          'Slow fiber speeds',
          'No adult home during dispatch window and lack of pre-install communication',
          'Rain on the roof',
          'Customers having too many TVs'
        ],
        correctAnswerIndex: 1,
        explanation: 'Over 80% of missed installs stem from the homeowner forgetting the appointment window or not having an adult present.'
      }
    ]
  }
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif_1',
    title: 'Install Completed & Verified! 🎉',
    message: 'Robert Vance Jr. (FB-98201) AT&T 1 Gig installed successfully. $260.00 commission added to pending payroll.',
    type: 'sale' as const,
    timestamp: '2026-09-23T16:45:00Z',
    read: false,
    linkTab: 'my-sales'
  },
  {
    id: 'notif_2',
    title: 'Texas Mega Blitz Milestone 🚀',
    message: 'Central Texas Blitz has crossed 300+ total sales! Team payout accelerator active.',
    type: 'blitz' as const,
    timestamp: '2026-09-24T12:00:00Z',
    read: false,
    linkTab: 'blitz-booking'
  },
  {
    id: 'notif_3',
    title: 'New Training Course Available 📚',
    message: 'Marcus Vance published "Order Accuracy, ONT Placement & Zero-Cancel Dispatching". Complete it to earn your badge!',
    type: 'course' as const,
    timestamp: '2026-09-24T18:30:00Z',
    read: true,
    linkTab: 'training'
  }
];

export const INITIAL_MESSAGES: InternalMessage[] = [
  {
    id: 'msg_1',
    senderId: 'user_mgr_marcus',
    senderName: 'Marcus Vance',
    senderRole: 'Manager',
    senderBadgePhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    recipientType: 'blitz_broadcast',
    recipientId: 'blitz_tx_central_surge',
    blitzId: 'blitz_tx_central_surge',
    blitzTitle: 'Central Texas & DFW Mega Blitz',
    title: '🚨 TURF DISPATCH: North Fort Worth Node Live!',
    content: 'Morning update team: All ONT terminals along Lone Star Trail & Bluebonnet Way are energized. Carrier technician shuttles are rolling out at 8:30 AM from the Omni lobby. Knocking authorized starting 9:00 AM sharp. Let\'s close 40+ today!',
    isPushAlert: true,
    priority: 'blitz_dispatch',
    createdAt: '2026-09-25T08:15:00Z',
    readBy: ['user_rep_jordan'],
  },
  {
    id: 'msg_2',
    senderId: 'user_mgr_marcus',
    senderName: 'Marcus Vance',
    senderRole: 'Manager',
    senderBadgePhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    recipientType: 'direct',
    recipientId: 'user_rep_jordan',
    recipientName: 'Jordan Hayes',
    title: 'Great work on the 2 Gig closing!',
    content: 'Hey Jordan, dispatch confirmed customer Patricia Morales was successfully provisioned with zero drop issues. Keep utilizing the symmetrical upload script on the corner homes today!',
    isPushAlert: false,
    priority: 'normal',
    createdAt: '2026-09-25T11:30:00Z',
    readBy: [],
  },
  {
    id: 'msg_3',
    senderId: 'user_owner_gurpreet',
    senderName: 'Gurpreet Multani',
    senderRole: 'Admin',
    senderBadgePhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    recipientType: 'company_broadcast',
    recipientId: 'all',
    title: '⚡ Weekend Accelerator: $500 Bonus for 20+ Installs',
    content: 'Executive announcement to all regional blitz squads: Any rep reaching 20+ verified installs by Sunday midnight receives an immediate $500 direct deposit performance accelerator on top of standard commission. Let\'s dominate the field!',
    isPushAlert: true,
    priority: 'urgent',
    createdAt: '2026-09-25T14:00:00Z',
    readBy: ['user_mgr_marcus', 'user_rep_jordan'],
  }
];
